[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ['-Clink-arg=-Tsrc/lds/virt.lds', '-Ctarget-feature=-c']

[target.riscv64gc-unknown-none-elf]
runner = """qemu-system-riscv64 -M virt -smp 1 -m 1G \
            -display none -serial pty \
            -bios none -kernel
            """
